//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInto
    {
        public string Id { get; set; }
        public string IdObject { get; set; }
        public string IdOutputInfo { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<int> Counts { get; set; }
        public string Status { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual OBJECT OBJECT { get; set; }
        public virtual Output Output { get; set; }
    }
}
